### ISSUE TITLE
When reading Contentstack API response, default system charset shouldn't be used 

### ISSUE THREAD

**Issue by kirmerzlikin** [contentstack/contentstack-java#18]
In the method `CSHttpConnection.sendGET()` new `InputStreamReader` is created without providing a charset. 
https://github.com/contentstack/contentstack-java/blob/030f8b348dbf56af7fdd5e7475448d68b82e1cc0/src/main/java/com/contentstack/sdk/CSHttpConnection.java#L294
According to [documentation](https://docs.oracle.com/javase/8/docs/api/java/io/InputStreamReader.html#InputStreamReader-java.io.InputStream-) in this case stream reader will use default system charset. Since default system charset depends on underlying OS (e.g. for linux it's UTF-8 and for Windows it's CP1250/CP1251/CP1252) and therefore doesn't always correspond to the actual charset of Contentstack API response, this may lead to **_incorrect response parsing_**.

I would suggest to explicitly set `UTF-8` charset when creating `InputStreamReader`, like this:
`new InputStreamReader(con.getInputStream(), StandardCharsets.UTF_8)`.

**Comment by ishaileshmishra** [comment]
@kirmerzlikin Thanks for creating issue, We will explicitly set UTF-8 charset so it does not lead to incorrect response parsing.
