### ISSUE TITLE
Querying content with `null` field

### ISSUE THREAD

**Issue by ondrejfuhrer** [contentstack/contentstack-java#23]
Hello there,

We have a use case where we need to query the content by specifying one of the fields as `null`. So the use case would be that you have a content with optional field and distinguish between having it filled in with certain value or not filled at all.

Example: 

ID | field1 | field2
---|------|------
1 | value1 | |
2 | value1 | value2 |

Q1: `?query={"field1": "value1", "field2": null}` will return id `1`
Q2: `?query={"field1": "value1", "field2":"value2"}` will return id `2`

I noticed that in the implementation you're currently using a `JSONObject.put` which in case I call `query.put("field1", null)` actually removed the key `field1` from the object instead of adding it as a value.

Is there currently a workaround how to query values like that (except querying all models that fit it and check for the field manually)?

**Comment by ishaileshmishra** [comment]
Thanks @ondrejfuhrer, for raising the issue. We will look into this.

**Comment by ondrejfuhrer** [comment]
@ishaileshmishra Thanks for a quick reply. After some investigation I found out, that in order to set the param to `null` what works is to set the value to `JSONObject.NULL` instance which works fine. Unfortunately that is not clear unless there is awareness of how you internally build the query in the SDK (i.e. that you use `JSONObject` to do that).

**Comment by ishaileshmishra** [comment]
Hi @ondrejfuhrer, Can you please give a try to the **notExists(field2)** function available in Query class, Do let me know if works for you ?

```
Stack stack = Contentstack.stack("api_key", "delivery_token", "environment");
Query query = stack.contentType(“content_type”).query();
query.notExists(“field2");
query.find(new QueryResultsCallBack() {
    @Override
    public void onCompletion(ResponseType responseType, QueryResult queryresult, Error error) {
           if (error == null) {
                    int entryCount = queryresult.getCount();
                    System.out.println(“count: “+entryCount);
                }
           }
});
```

**Comment by ondrejfuhrer** [comment]
Hello @ishaileshmishra 
Thank you for the suggestion. That unfortunately doesn't work as in that case the field does exist, but it its value is `null`. What you are suggesting would work only in case the field is not present. So lets say those are my entries:

```json
{
    "entries": [
        {
            "_in_progress": false,
            "_version": 1,
            "locale": "en-us",
            "param2": null,
            "created_at": "2020-02-17T15:58:11.891Z",
            "param1": "value1",
            "updated_at": "2020-11-17T11:09:28.992Z"
        },
        {
            "locale": "en-us",
            "_in_progress": false,
            "_version": 1,
            "param2": "value2",
            "created_at": "2020-02-19T17:30:29.213Z",
            "param1": "value1",
            "updated_at": "2020-02-19T17:30:29.213Z",
        }
    ]
}
``` 

And I would like to build a query with `?query={"param1": "value1", "param2": null}` in order to select the first entry.

Currently the only way how I made it work is by using this:
```java
Stack stack = Contentstack.stack("api_key", "delivery_token", "environment");
Query query = stack.contentType(“content_type”).query();
query.addParam("param1", "value1");
query.addParam("param2", JSONObject.NULL);
query.findOne(new SingleQueryResultsCallBack() {
    @Override
    public void onCompletion(ResponseType responseType, Entry entry, Error error)
        if (error == null) {
            System.out.println(“Entry: “+entry);
        }
     }
});
```

**Comment by ishaileshmishra** [comment]
Noted @ondrejfuhrer, We will look into this.

**Comment by ondrejfuhrer** [comment]
Any update on this?
