### ISSUE TITLE
Retreive Asset with dimensions

### ISSUE THREAD

**Issue by AurelienLoth** [contentstack/contentstack-java#24]
Hi,

it seems to be impossible to retreive Asset with dimensions.

With REST API, I can : 

`https://{{base_url}}/v3/assets/blt3e12cb887266e3ff?environment={{environment}}&include_dimension=true`

but with the SDK I can't add the parameter.

I suggest to fix it in modifying Asset, the fetch method to add

```
if (headers.containsKey("include_dimension")) {
    urlQueries.put("include_dimension", true);
}
```
Regards

**Comment by uttamukkoji** [comment]
Thanks @AurelienLoth, for raising the issue. We’re looking into it and we’ll push a fix as early as possible.
