### ISSUE TITLE
Language/LanguageCode enum, typos and missing data

### ISSUE THREAD

**Issue by feliperuiz** [contentstack/contentstack-java#27]
The `Language` enum has a typo for the German language; all variants are [written as `GERMEN`](https://github.com/contentstack/contentstack-java/blob/57f34d7137bb2ce1d5b8e72974a66d05cbdeca8c/src/main/java/com/contentstack/sdk/Language.java#L132-L140) when the correct would be `GERMAN`.

Some [supported languages](https://www.contentstack.com/docs/developers/multilingual-content/list-of-supported-languages/), such as Norwegian (`no-no`), are also missing from the both `Language` and `LanguageCode`. The list of supported languages contains 233 items, whereas the enums only contain 136 each.

**Comment by ishaileshmishra** [comment]
@feliperuiz thanks for raising the issue. **setLanguage** is deprecated since **v1.4.0**, To use locale you can write like.

**entry.setLocale("no-no");**

Example: 
```
Stack stack = Contentstack.stack(apiKey, deliveryToken, environment);
final Entry entry = stack.contentType("content_type").entry("entry_uid")
entry.setLocale("no-no");
query.find(new QueryResultsCallBack() {
            @Override
            public void onCompletion(ResponseType responseType, QueryResult queryresult, Error error) {
                if (error == null) {
                    List<Entry> listOfEntries = queryresult.getResultObjects();
                    logger.fine(listOfEntries.toString());
                }
            }
        });
```

hope it will be helpful for you.

**Comment by feliperuiz** [comment]
But the enums themselves are not deprecated, so you can see how that can lead to confusion. Perhaps deprecating them as well would make it clearer that they are not meant to be used, not only the method.

**Comment by ishaileshmishra** [comment]
@feliperuiz thanks, for mentioning. It will be marked as Deprecated in the next version soon.
