### ISSUE TITLE
Version 1.7.0 released?

### ISSUE THREAD

**Issue by ondrejfuhrer** [contentstack/contentstack-java#33]
Hello,

Last week we got a version bump notification from dependabot that version `1.7.0` has been released. However there is no such release in GitHub, no changelog, also last update to the `master` branch has been done on 6th of April. Can someone look into it and se what happened here? Is the `1.7.0` really the most recent version?

**Comment by ishaileshmishra** [comment]
Yes, @ondrejfuhrer 1.7.0 is the latest version.

**Comment by oscarryz** [comment]
It seems the source of confusion is tag v1.7.0 points to the same commit as v1.6.0 of April 6th, instead of   63d000b9b14fc41732d6ecb97733f57ea088e265 where the pom.xml was updated.

**Comment by ishaileshmishra** [comment]
@oscarryz, There are no updates in the sdk despite the updated utils package in the pom.xml file.

**Comment by ondrejfuhrer** [comment]
@ishaileshmishra If I understand correctly what @oscarryz meant is that the tag 1.7.0 here on github points to the same commit as 1.6.0 -> https://github.com/contentstack/contentstack-java/commit/c84e22815136e94579769604d3185aa3955677f3 

That is probably not correct.

**Comment by ishaileshmishra** [comment]
Thanks for mentioning @ondrejfuhrer. I will look into this.
