### ISSUE TITLE
Version 1.8.0?

### ISSUE THREAD

**Issue by feliperuiz** [contentstack/contentstack-java#37]
Hey, Contentstack team! We recently got notified by dependabot that version 1.8.0 of the SDK had been released, but the latest public commit in the project is from September 9, and the latest tag is from July 19. Similar to #33, there is no changelog, release notes, anything like that. Is 1.8.0 legit?

**Comment by ishaileshmishra** [comment]
Thanks for creating the issue @feliperuiz. We would like to inform you that we have updated the java dependency yesterday. The code is going through necessary SDLC checks. We expect to merge it soon with the master

**Comment by ishaileshmishra** [comment]
Updated code merged to the master. v1.8.0 released and tag created. closing the issue. You can reopen the issue in case of any queries. thanks.
