### ISSUE TITLE
Entry serialisation issue

### ISSUE THREAD

**Issue by TeodorTunev** [contentstack/contentstack-java#43]
Hey CS team, we update our sdk to 1.8.0, because of log4j issue, but we notice few changes on the **Entry** and **ContentType** classes that the logger inside is no longer static. That cause an issue with our cache, what we are doing is to pull some of the common entries in our system and cache in redis to avoid trafic for most common entries, but since the logger is part of the instance when we put to our cache the Entry is serialised with Jackson and its throw self-reference error 

`com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Direct self-reference leading to cycle (through reference chain: com.contentstack.sdk.Entry["contentType"]->com.contentstack.sdk.ContentType["logger"]->java.util.logging.Logger["config"]->java.util.logging.Logger$ConfigurationData["delegate"])`

Is there any particular reason to change that logger? And if not can we change it somehow to avoid that serialisation issue.

**Comment by ishaileshmishra** [comment]
Thanks for writing us @TeodorTunev. Although this is a unique way of using the logger instance, We will have a look at the above request and update if we find a work-around.

**Comment by TeodorTunev** [comment]
Something else that we also notice is that the default contructors for Entry, ContentType and Stack throw exception, which prevent us from customise jackson mapper, because its require to have empty constructor to be able to build it.

**Comment by ishaileshmishra** [comment]
The issue has been fixed in v1.8.1, Please to the latest version
