### ISSUE TITLE
Reverse logic for missing uid

### ISSUE THREAD

**Issue by TeodorTunev** [contentstack/contentstack-java#45]
Hello, we have notice that SDK 1.8.0 generate a lot of error for **Entry Uid is required**, after debugging it we found out that the logic for empty uid is wrong here - https://github.com/contentstack/contentstack-java/blob/master/src/main/java/com/contentstack/sdk/Entry.java#L955 , its check if its **not** empty, then throw an error. Can we release minor version with the fix please, we need 1.8.0, because of log4j update, but our logs are full of that error.

**Comment by ishaileshmishra** [comment]
Thanks for writing to us @TeodorTunev. We have noticed the issue. We will fix it earliest and update you.

**Comment by TeodorTunev** [comment]
Hello, I see that you fix the bug, when you plan to release the version?

**Comment by ishaileshmishra** [comment]
@TeodorTunev We are scheduling to release it by end of the month.

**Comment by ishaileshmishra** [comment]
The issue has been fixed in v1.8.1, Please to the latest version
