### ISSUE TITLE
"environment" is removed from header in getService() in version 1.8.x

### ISSUE THREAD

**Issue by zxm5010** [contentstack/contentstack-java#47]
We upgraded from 1.4 to 1.8 recently, and noticed an issue in recent 1.8.x versions that the following fetches after first one fails because of error: `"error_message":"Failed to fetch entries. Please try again with valid parameters.","error_code":141,"errors":{"environment":["is required."]}}`

I think this line causes an issue https://github.com/contentstack/contentstack-java/blob/0e3d917bd8ea1564cd8938d81d3ac682ecec55ef/src/main/java/com/contentstack/sdk/CSHttpConnection.java#L187

The "environment" gets removed from any `getService` call, which causes the issue.

We have a workaround now is to call `setHeader` every time before making fetch calls, please provide a fix for it. Thank you!

**Comment by ishaileshmishra** [comment]
Hi, @zxm5010 thanks for writing us. We have removed the **environment from the header**. As per the documentation **environment should go with Query Parameters** see the [documentation](https://www.contentstack.com/docs/developers/apis/content-delivery-api/#get-all-entries).

**Comment by ishaileshmishra** [comment]
1  - You don't need to add environment as a query param. we handle it internally.
2  - We are looking into it the issue you are getting api_key error. 

We are trying to reproduce the said issue at our end

**Comment by zxm5010** [comment]
@ishaileshmishra 

1 - Quick clarification, we are always getting ```"error_message":"Failed to fetch entries. Please try again with valid parameters.","error_code":141,"errors":{"environment":["is required."]}}```  after the first `fetch` request, unless if we set header explicitly. I think there's something overwrites stack's context/header internally when we do fetches. Maybe it also relates to api_key error


For more context, we are fetching nested contents. And, nested fetches are called in the onCompletion method. 

Example:

```
stack.contentType("root_content").query().find(
     new QueryResultsCallback() {
         public void onCompletion(ResponseType responseType, QueryResult queryResult, Error error) {
             if (error == null) {
                 //Success block
                 List<Entry> results = queryResult.getResultObjects();
                 for (Entry entry : results) {
                     JSONArray childrenContentRefs = entry.getJSONArray("children_content_refs");
                     for(int i = 0; i < childrenContentRefs.length(); i++) {
                         String uid = refs.getJSONObject(i).getString("uid");
                         Entry entry = stack.contentType("children_content").entry(uid);   
                         // ... logic dealing with children entry are truncated. 
                      }
                 }   
              } else {
                 //Error block
              }
         }
     }
)
```

Not sure if there's any behavior changes internally how the requests getting handled, but the logic mentioned above is working fine in version 1.4.x, but failing 1.8.x

**Comment by ishaileshmishra** [comment]
@zxm5010 Please update your [contentstack-java](https://search.maven.org/artifact/com.contentstack.sdk/java/1.9.0/jar) dependency to v1.9.0, 
Feel free to reopen the issue if your issue is not resolved.
