### ISSUE TITLE
Fail to initialize EntryModel when i have a group field uid called description

### ISSUE THREAD

**Issue by linnwong** [contentstack/contentstack-java#48]
In EntryModel.java, line 59, if I have a group field UID called `description` it would fail with a casting error because group field will be of JSONObject type and on the code base, it is expecting `description` to be a String data type instead.

![image](https://user-images.githubusercontent.com/5687145/153746736-fb2dbfcc-18a9-44a1-81b5-2da22c4f5fe3.png)

**Comment by ishaileshmishra** [comment]
Hi, @linnwong thanks for writing us. We will look into it and update you once it is resolved.

**Comment by ishaileshmishra** [comment]
@linnwong Please update your [contentstack-java](https://search.maven.org/artifact/com.contentstack.sdk/java/1.9.0/jar) dependency to v1.9.0, 
Feel free to reopen the issue if your issue is not resolved.
