### ISSUE TITLE
High increase in memory consumption & thread count when updated to the `1.9.0` version

### ISSUE THREAD

**Issue by ondrejfuhrer** [contentstack/contentstack-java#52]
Hello team,

We’re currently running version `1.7.0` of your SDK without any issues. We tried to upgrade to the newest version this week, however after deploying the version we could see immediately a high increase on opened threads & increased memory usage for each running pod. Here you can see the reported avg thread count for the deployed period (14:55 we started rolling out the version `1.9.0`, at around 15:12 we started rolling out the previous version). 
![ScreenCapture at Wed Mar 23 15:30:53 CET 2022](https://user-images.githubusercontent.com/10830505/161036698-178b8a4f-5c3f-4172-9364-ff97f2f4c28d.png)

At the same time memory consumption of each pod went approx. 50% up (I mean, needs to handle all the active threads etc), which leads me to an assumption that we might be facing some sort of resource leak in the library. Or is that something expected from your end? It’s hard to correlate any changelog items to this.

Also worth mentioning: We also tested other versions and it seems to have the same issues, so the issue was probably introduced in the version `1.8.0`.

**Comment by ishaileshmishra** [comment]
thanks for raising the issue, we are looking into it. @ondrejfuhrer

**Comment by ondrejfuhrer** [comment]
Hey @ishaileshmishra any update on this? It's more then a month without any update 😞

**Comment by ishaileshmishra** [comment]
Hi @ondrejfuhrer, We have made some changes in the code that might be helpful for you. We are in the process to release a newer version of dependency by next week

**Comment by vitorsdcs** [comment]
Hi @ishaileshmishra, it looks like there is no new release yet. Can you provide us any updates on this? Thanks.

**Comment by ishaileshmishra** [comment]
Hi @vitorsdcs @ondrejfuhrer,  Please update the SDK to v1.10.0 and let us know if it solved the issue.

**Comment by ondrejfuhrer** [comment]
Hey @ishaileshmishra , thank you for that. Created a different issue with `1.10.0` preventing us from actually trying it out. Can you please look at it? https://github.com/contentstack/contentstack-java/issues/57

**Comment by ondrejfuhrer** [comment]
Hey @ishaileshmishra , just wanted to let you know, that it seems all the issues we had with the latest release are fixed and looking great. Thank you for your support 🙂
