### ISSUE TITLE
Invalid warning for contentTypeUid

### ISSUE THREAD

**Issue by gurban-h** [contentstack/contentstack-java#58]
https://github.com/contentstack/contentstack-java/blob/16fe5c54552c8ec033b12153b14f318c1e6353a1/src/main/java/com/contentstack/sdk/ContentType.java#L128-L134

Condition for checking the parameter is incorrect, and doesn't match with the warning message. It must be
```java
if (contentTypeUid == null || contentTypeUid.isEmpty()) {
    logger.warning("contentTypeUid is required");
}
```

It is not clear to me why an exception is thrown and caught there not to be used.
Also if `contentTypeUid` is required why it is logged as `warning`?

**Comment by ishaileshmishra** [comment]
thanks for writing us @gurban-h, We will update the code.
