### ISSUE TITLE
Support for updating Entry

### ISSUE THREAD

**Issue by gurban-h** [contentstack/contentstack-java#60]
Hi there.

Does this SDK support [updating an entry](https://www.contentstack.com/docs/developers/apis/content-management-api/#update-an-entry) yet? If not, is there plan and estimate of supporting it?

Thanks,

**Comment by ishaileshmishra** [comment]
Thanks for writing us @gurban-h, 
This SDK is for the **content delivery** APIs, So it does not provide support for entry updates. Hence we are closing the [issue](https://github.com/contentstack/contentstack-java/issues/60) 

> Note: We have a plan to release SDK that supports **content management** APIs.

**Comment by gurban-h** [comment]
Thanks @ishaileshmishra . Do you have timeline for releasing "SDK that supports content management API"?
