### ISSUE TITLE
Followup on issue: Support for updating Entry #60

### ISSUE THREAD

**Issue by DanaVisan** [contentstack/contentstack-java#62]
Hello ContentStack Team,

I am reaching out to [follow-up on an issue](https://github.com/contentstack/contentstack-java/issues/60) that was raised but closed before the final question was answered.
Can you please let me know if you have a timeline for [updating the SDK for content delivery](https://www.contentstack.com/docs/developers/apis/content-management-api/#update-an-entry)?

I look forward to hearing from you.
Best regards,
Dana

**Comment by ishaileshmishra** [comment]
Hi @DanaVisan, We have released Java-management-SDK, It's available [here](https://central.sonatype.dev/artifact/com.contentstack.sdk/cms/0.1.0). Please try it out. We appreciate your feedback on it.
