### ISSUE TITLE
error handling infinite loop issue

### ISSUE THREAD

**Issue by oscar2song** [contentstack/contentstack-java#67]
We experienced  high CPU usage issue on our production when publishing events were happening after we upgraded the com.contentstack.sdk to the new version:
<p>
<dependency>
    <groupId>com.contentstack.sdk</groupId>
    <artifactId>java</artifactId>
    <version>1.10.1</version>
</dependency>
 </p>
after investigation, we found the issue is from the following code that caused error handling infinite loop when we fetch resources from contentstack, which in further caused the some piece of memory never released and also made the thread never released until our CMS application was killed/restarted.
 
We have a workaround solution to make changes of the source code to solve the issue.
 
Here is the origin code [com.contentstack.sdk.Query# execQuery](https://github.com/contentstack/contentstack-java/blob/d2b157438c17d189f38a98e54e5a53bc96be8776/src/main/java/com/contentstack/sdk/Query.java#L1234)
 
Here is our customed code:

```
protected void execQuery(SingleQueryResultCallback callBack, QueryResultsCallBack callback) {
        String urlString = "content_types/" + contentTypeUid + "/entries";
        queryResultCallback = callback;
        singleQueryResultCallback = callBack;
        setQueryJson();
        urlQueries.put(Constants.ENVIRONMENT, this.headers.get(Constants.ENVIRONMENT));
        includeLivePreview();
        mainJSON.put(QUERY, urlQueries);
        fetchFromNetwork(urlString, mainJSON, callback, callBack);
}
```
 
The main difference is removing the try catch to allow exception to be thrown out from ContentStack SDK to give a user opportunity to control exception and do some retries when an error occurs.
 
For example:

```
public ContentStackQueryService(Query query) {
    this.query = query.limit(Pagination.PAGE_SIZE).includeCount(); // ensure we do have count
    this.callBack = new QueryResultsCallBack() {
        @Override
        public void onCompletion(ResponseType responseType, QueryResult queryresult, Error error) {
            if (error != null) {
                final String failedMsg = String.format("Query failed: ResponseType=%s, ErrorCode=%s, ErrorMessage=%s, ErrorDetail=%s,", responseType, error.getErrorCode(), error.getErrorMessage(), error.getErrorDetail());
                throw new RuntimeException(failedMsg); // in this way, we will retry unless we failed finally
            } else {
                int itemsTotalCount = queryresult.getCount();
                if (itemsTotalCount == 0) {
                    endOfResults.set(true); // no results
                    return;
                }
   ‘’’’’’’
```

please make some changes and fix the issue in this SDK, we will upgrade the SDk once you update the code and publish a new version in maven repository.
 
Thanks
Oscar Song

**Comment by ishaileshmishra** [comment]
Thank you for bringing this to my attention @oscar2song. I will promptly address the matter and provide an update once the necessary changes have been implemented.

**Comment by ishaileshmishra** [comment]
Update your **contentstack-java** dependency to [v1.11.0](https://mvnrepository.com/artifact/com.contentstack.sdk/java/1.11.0). Closing this issue, but please don't hesitate to reopen it if the problem remains unresolved. @oscar2song
