### ISSUE TITLE
Remove catching of exception on Entry fetch

### ISSUE THREAD

**Issue by Scorze** [contentstack/contentstack-java#78]
Hi everyone,
I saw that as part of issue https://github.com/contentstack/contentstack-java/issues/67 the try catch mechanism for the method fetchFromNetwork has been removed from the Query class to allow handling and retries of different types of exceptions. Can we have the same done for Entry as well?

This is the piece of code I'm referring to 
```
    private void fetchFromNetwork(String urlString, JSONObject urlQueries, EntryResultCallBack callBack) {
        try {
            JSONObject mainJson = new JSONObject();
            setIncludeJSON(urlQueries, callBack);
            mainJson.put("query", urlQueries);
            HashMap<String, Object> urlParams = getUrlParams(mainJson);
            new CSBackgroundTask(this, contentType.stackInstance, Constants.FETCHENTRY, urlString, this.headers,
                    urlParams, Constants.REQUEST_CONTROLLER.ENTRY.toString(), callBack);
        } catch (Exception e) {
            throwException(null, e, callBack);
        }
    }
```
So from this, the try-catch would be removed.

Thank you!

**Comment by ishaileshmishra** [comment]
Thank you for writing us @Scorze. If the proposed solution proves effective, I will incorporate the necessary code changes and include them in the upcoming build.

**Comment by ishaileshmishra** [comment]
The issue has been resolved in the latest version.
