### ISSUE TITLE
Entry not getting created from CS Management  API - Java SpringBoot Application

### ISSUE THREAD

**Issue by lalatendujena** [contentstack/contentstack-java#85]
I am using the below code to create an entry in CS, but I am not sure what the issue is, only the empty Entry is getting created.

        ProductPayloadContentStackDto productPayload = mapper.map(product);
        Random random = new Random();
        productPayload.setTitle("TestApp"+random.ints());
        productPayload.setLocale("en-us");
        productPayload.setUrl("atgghygh");
        Contentstack contentstack = new Contentstack.Builder().build();
        Stack stack = contentstack.stack(stackApiKey, managementToken);
        Entry entry = stack.contentType("product").entry();
        JSONObject prodRequest = new JSONObject();
        org.json.JSONObject entryObj;
        try {
          entryObj = new org.json.JSONObject(new ObjectMapper()
              .writeValueAsString(productPayload));
        } catch (JSONException | JsonProcessingException e) {
          throw new RuntimeException(e);
        }
        
        prodRequest.put("entry", entryObj);
        Response<ResponseBody> responseFromCs;
        try {
          responseFromCs = entry.create(prodRequest).execute();
        } catch (IOException e) {
          throw new RuntimeException(e);

The entryObj has a couple of values inside.

**Comment by ishaileshmishra** [comment]
Thank you for bringing up the issue. The matter mentioned above doesn't pertain to the current SDK; rather, it is associated with the Contentstack-Management-Java SDK. We will investigate this matter further.

**Comment by lalatendujena** [comment]
Thanks for the response. The issue got resolved now. When we were creating entries from SDK, we needed a key-value pair for the JSON object, and the value for us was a separate map. So we have handled this on the Java side now. Thank you.
